on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  clean_and_fill:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clean directory
        run: |
          rm -rf docs/pages/*

      - name: Build doc
        run: |
          ./build.sh

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: commit push
        run: |
          git commit -m "Update doc"
          git push origin main