on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  build-the-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clean directory
        run: |
          rm -rf docs/pages/*

      - name: Build doc
        run: |
          pip3 install Markdown
          ./build.sh

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: commit push
        run: |
          rm -r docs/source docs/mds
          ls
          echo ---
          rm -r raw .github
          ls 
          echo ---
          rm .gitignore build.sh open.sh README.md requirements.txt 
          ls
          
          git add /docs/pages
          git add /docs/index.html
          
          git commit -m "Update doc"
          git push origin main