name: Build and Deploy Docs
permissions:
  actions: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip3 install -r requirements.txt


      - name: Run build script
        run: ./build.sh

      - name: Deploy to gh-pages branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git add doc/pages
          git add doc/home.html
          git add doc/rsc
          git commit -m "Update documentation"
          git push -f origin gh-pages
          git checkout main