on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  build-the-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clean directory
        run: |
          rm -rf docs/pages/*

      - name: Build doc
        run: |
          pip3 install -r requirements.txt
          cd docs; ./build.sh; cd ..

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: checkout gh-pages
        run: |
          git checkout -b gh-pages

      - name: clean
        run: |
          rm -r docs/mds docs/source docs/build.sh
          rm -r raw .github
          rm .gitignore requirements.txt 

      - name: commit push
        run: |
          git add .
          git commit -m 'Update doc'
          git push --force origin gh-pages