name: Build and Deploy Docs


on:
  push:
    branches:
      - main
permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip3 install -r requirements.txt


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the folder using the script
        run: |
          ./build.sh
          ls

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Create and switch to the new branch
        run: |
          git checkout gh-pages

      - name: Copy the contents to the new branch
        run: |
          cp -r doc/pages/* .

      - name: Commit and push to the new branch
        run: |
          git add .
          git commit -m "Build and deploy the folder"
          git push origin gh-pages